version: '3.7'
services:
  arango:
    #platform: linux/amd64
    #image: arangodb:3.7.12

    #note: if you need to upgrade the database, run: docker-compose -f arangodb.yml run --rm arangodb_db_container --database.auto-upgrade
    image: arangodb:3.10.1
    environment:
      ARANGO_ROOT_PASSWORD: secret
    ports:
      - 8529:8529
    volumes:
      - .volumes/arangodb3/data:/var/lib/arangodb3
      - .volumes/arangodb3/apps_container:/var/lib/arangodb3-apps