
name: Build and Deploy to GKE

on:
  push:
    tags:
    - '*'
    branches:
    - main

jobs:
  build-and-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Git user config
      run: |-
        git config --global user.email "tinybuilder@productdock.com"
        git config --global user.name "TinyBuilder"

    - name: update package version
      run: |-
        yarn update:package $GITHUB_REF_NAME
        yarn update:package:app $GITHUB_REF_NAME
        yarn update:package:dashboard $GITHUB_REF_NAME
        yarn update:package:middleware $GITHUB_REF_NAME
        yarn update:package:plugins:core $GITHUB_REF_NAME
        yarn update:package:plugins:essentials $GITHUB_REF_NAME
      if: startsWith(github.event.ref, 'refs/tags/')
    
    - name: debug
      run: |-
        echo "ref is: " ${{ github.event.ref }}
    # Setup git credentials
    
    # increment package version and publish
    # - name: set yarn version
    #   run: |-
    #     echo "using version $GITHUB_REF_NAME"
    #     yarn version --new-version $GITHUB_REF_NAME

    # Build
    # - name: set yarn version
    #   run: |-
    #     yarn build:docker